# Generated by Django 4.1.4 on 2022-12-30 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=45)),
                ('player_nationality', models.CharField(blank=True, max_length=45, null=True)),
                ('player_personaname', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'players',
                'managed': False,
            },
        ),
    ]
