# Generated by Django 4.1.4 on 2022-12-30 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotainfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueDetails',
            fields=[
                ('league_id', models.IntegerField(primary_key=True, serialize=False)),
                ('league_name', models.CharField(blank=True, max_length=45, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('is_finished', models.IntegerField()),
            ],
            options={
                'db_table': 'league_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LeagueGames',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('radiant_win', models.IntegerField(blank=True, null=True)),
                ('radiant_team', models.IntegerField()),
                ('dire_team', models.IntegerField()),
                ('game_duration', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'league_games',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerResults',
            fields=[
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotainfo.players')),
                ('kills', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('assists', models.IntegerField(blank=True, null=True)),
                ('last_hits', models.IntegerField(blank=True, null=True)),
                ('gold_per_minute', models.IntegerField(blank=True, null=True)),
                ('xp_per_minute', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_results',
                'managed': False,
            },
        ),
    ]
