# Generated by Django 4.1.4 on 2023-01-03 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotainfo', '0002_leaguedetails_leaguegames_playerresults'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerresults',
            options={},
        ),
    ]
