# Generated by Django 4.1.4 on 2023-01-03 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dotainfo', '0003_alter_playerresults_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerresults',
            options={'managed': False},
        ),
    ]
