# Generated by Django 4.1.4 on 2023-01-03 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dotainfo', '0004_alter_playerresults_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerScore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'player_score',
                'managed': False,
            },
        ),
    ]
