# Generated by Django 4.1.4 on 2023-01-02 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dotainfo', '0002_leaguedetails_leaguegames_playerresults'),
        ('users', '0002_alter_userinfo_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersTeam',
            fields=[
                ('user_team_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_team_name', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'users_team',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersTeamPlayers',
            fields=[
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='dotainfo.leaguedetails')),
                ('player_1', models.IntegerField(blank=True, db_column='player 1', null=True)),
                ('player_2', models.IntegerField(blank=True, db_column='player 2', null=True)),
                ('player_3', models.IntegerField(blank=True, db_column='player 3', null=True)),
                ('player_4', models.IntegerField(blank=True, db_column='player 4', null=True)),
                ('player_5', models.IntegerField(blank=True, db_column='player 5', null=True)),
                ('player_6', models.IntegerField(blank=True, db_column='player 6', null=True)),
            ],
            options={
                'db_table': 'users_team_players',
                'managed': False,
            },
        ),
    ]
