# Generated by Django 4.1.4 on 2023-01-02 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usersteam_usersteamplayers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersteam',
            options={},
        ),
    ]
