# Generated by Django 4.1.4 on 2023-01-02 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usersteam_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersteam',
            options={'managed': False},
        ),
    ]
