# Generated by Django 4.1.4 on 2022-12-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.TextField(default='test'),
        ),
    ]
