# Generated by Django 4.1.4 on 2022-12-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_main_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='about',
            field=models.TextField(default='-'),
        ),
        migrations.AddField(
            model_name='main',
            name='fb',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='main',
            name='link',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='main',
            name='tell',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='main',
            name='tw',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AddField(
            model_name='main',
            name='yt',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='main',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
