# Generated by Django 4.1.4 on 2022-12-27 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_authuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='favpicname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='main',
            name='favpicurl',
            field=models.TextField(default=''),
        ),
    ]
